routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\ArticlesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::resource('articles', ArticlesController::class);

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use HasFactory;
    use SoftDeletes;

    public function user() {
        return $this->belongsTo('App\Models\User');
    }

    protected $fillable = ['title', 'content', 'state'];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array<int, string>
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function articles() {
        return $this->hasMany('App\Models\Article');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\User;

class ArticlesController extends Controller
{
    // 控制器創建時自動呼叫 只有登入後才能訪問 例外()
    public function __construct()
    {
        $this->middleware(middleware: 'auth')->except(['index', 'show']);
    }
    // 文章列表
    public function index()
    {
        // 檢查參數中是否包含edit
        $hasEdit = request()->has('edit');
        // 檢查是否有搜尋參數
        $hasSearch = request('search');
        // 如果有edit 顯示你的文章
        if ($hasEdit) {
            $articles = User::find(auth()->id())->articles()->orderBy('id', 'desc');
        } else {
            // 否則 顯示所有人已發布的文章列表
            $articles = Article::where('state', '=', 'published')->orderBy('id', 'desc')->with('user');
        }
        // 如果有搜尋參數 進行搜尋
        if ($hasSearch) {
            $articles->where('title', 'like', '%' . $hasSearch . '%')
                ->orWhere('content', 'like', '%' . $hasSearch . '%');
        }
        // 使用 paginate() 方法取得分頁結果
        $articles = $articles->paginate(8);
        return view('articles/index', ['articles' => $articles, 'hasSearch' => $hasSearch]);
    }
    // 詳細文章
public function show($id)
{
    // 使用 auth()->id() 獲取當前登入者的 ID
    $article = Article::where('id', $id)
                      ->where(function ($query) {
                          $query->where('state', 'published')
                                ->orWhere(function ($query) {
                                    $query->where('state', 'draft')
                                          ->where('user_id', auth()->id());
                                });
                      })
                      ->first();
        if (!$article) {
            abort(404, '文章不存在');
        }
        return view('articles.show', ['article' => $article]);
    }
    // 新增文章-表單視圖
    public function create()
    {
        return view('articles/create');
    }
    // 新增文章
    public function store(Request $request)
    {
        $content = $request->validate([
            'title' => 'required|max:100',
            'content' => 'required|max:500',
            'state' => ['required', 'in:draft,published'],
        ]);
        User::find(auth()->id())->articles()->create([
            'title' => $content['title'],
            'content' => $content['content'],
            'state' => $content['state'],
        ]);
        return redirect()->route('articles.index')->with('notice', '文章新增成功');
    }
    // 編輯文章-表單視圖
    public function edit($id)
    {
        $article = auth()->user()->articles->find($id);
        return view('articles.edit', ['article' => $article]);
    }
    // 編輯文章
    public function update(Request $request, $id)
    {
        $article = auth()->user()->articles->find($id);
        $content = $request->validate([
            'title' => 'required|max:100',
            'content' => 'required|max:500',
            'state' => ['required', 'in:draft,published'],
        ]);
        $article->update([
            'title' => $content['title'],
            'content' => $content['content'],
            'state' => $content['state'],
        ]);
        return redirect()->route('articles.index')->with('notice', '文章編輯成功');
    }
    // 刪除文章
    public function destroy($id)
    {
        $article = auth()->user()->articles->find($id);
        $article->delete();
        return redirect()->route('articles.index')->with('notice', '文章刪除成功');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view('home');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/articles/create.blade.php
@extends('layouts/article')

@section('main')

<!-- 錯誤提示 -->
@if($errors->any())
@foreach($errors->all() as $error)
<div class="alert alert-danger alert-dismissible fade show" role="alert">
<i class="bi bi-exclamation-triangle-fill"></i>&nbsp;{{ $error }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endforeach
@endif

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">新增文章</h2>
      <form action="{{ route('articles.store') }}" method="post">
        @csrf
        <div class="mb-3">
          <label for="title" class="form-label">標題:</label>
          <input type="text" class="form-control" id="title" name="title" placeholder="請輸入標題" value="{{ old('title') }}" maxlength="100" required>
        </div>
        <div class="mb-3">
          <label for="content" class="form-label">文章內容:</label>
          <textarea class="form-control" id="content" name="content" rows="3" placeholder="請輸入文章內容" maxlength="500" required>{{ old('content') }}</textarea>
        </div>
        <div class="mb-3 d-flex flex-row align-items-center">
          <span class="me-3">文章狀態:</span>
          <div class="form-check me-3">
            <input class="form-check-input" type="radio" name="state" id="state1" value="published" checked>
            <label class="form-check-label" for="state1">
              發布
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="state" id="state2" value="draft">
            <label class="form-check-label" for="state2">
              草稿
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">確認新增</button>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/articles/edit.blade.php
@extends('layouts/article')

@section('main')

<!-- 錯誤提示 -->
@if($errors->any())
@foreach($errors->all() as $error)
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <i class="bi bi-exclamation-triangle-fill"></i>&nbsp;{{ $error }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endforeach
@endif

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2 class="mb-4">編輯文章</h2>
      <form action="{{ route('articles.update', ['article' => $article->id]) }}" method="post">
        @method('PATCH')
        @csrf
        <div class="mb-3">
          <label for="title" class="form-label">標題:</label>
          <input type="text" class="form-control" id="title" name="title" value="{{ $article->title }}" maxlength="100" required>
        </div>
        <div class="mb-3">
          <label for="content" class="form-label">文章內容:</label>
          <textarea class="form-control" id="content" name="content" rows="3" maxlength="500" required>{{ $article->content }}</textarea>
        </div>
        <div class="mb-3 d-flex flex-row align-items-center">
          <span class="me-3">文章狀態:</span>
          <div class="form-check me-3">
            <input class="form-check-input" type="radio" name="state" id="state1" value="published" {{ $article->state == 'published' ? 'checked' : ''}}>
            <label class="form-check-label" for="state1">
              發布
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="state" id="state2" value="draft" {{ $article->state == 'draft' ? 'checked' : ''}}>
            <label class="form-check-label" for="state2">
              草稿
            </label>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">確認編輯</button>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/articles/index.blade.php
@extends('layouts/article')

@section('main')
<!-- 新增成功提示框 -->
@if(session('notice'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <i class="bi bi-check-circle-fill"></i>&nbsp;{{ session('notice') }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
@endif
<!-- 如果沒有edit的參數就顯示所有文章的文章列表 -->
@if(!request()->has('edit'))
<div class="table-responsive container">
    <table class="table row mx-auto table-striped table-hover">
        <thead>
            <tr class="row">
                <th class="col-md-8 col-6">文章</th>
                <th class="col-md-2 col-2">作者</th>
                <th class="col-md-2 col-4">發布時間</th>
            </tr>
        </thead>
        @if($articles->isEmpty())
        <tbody>
            <tr class="row">
                <td class="col-md-12 col-12" style="text-align: center;">暫無文章</td>
            </tr>
        </tbody>
        @else
        <tbody>
            @foreach($articles as $article)

            <tr class="row">
                <td class="col-md-8 col-6">
                    <a href="{{ route('articles.show', $article) }}">
                        <div class="text-truncate">
                            <strong style="font-size: 1.1em">{{ $article->title }}</strong><br>
                            {{ $article->content }}
                        </div>
                    </a>
                </td>
                <td class="col-md-2 col-2">
                    <div style="line-height:3;">{{ $article->user->name }}</div>
                </td>
                <td class="col-md-2 col-4">
                    <div class="text-truncate" style="line-height:3;">{{ $article->created_at }}</div>
                </td>
            </tr>
            @endforeach
        </tbody>
        @endif
    </table>
</div>
<!-- 分頁按鈕 -->
<div class="pagination">
    <ul>
        @if ($articles->onFirstPage())
        <li class="disabled"><span>&laquo;</span></li>
        @else
        <li><a href="{{ $articles->previousPageUrl() }}" rel="prev">&laquo;</a></li>
        @endif

        @php
        // 計算起始和結束頁數
        $start = max(1, $articles->currentPage() - 2);
        $end = min($articles->lastPage(), $articles->currentPage() + 2);
        @endphp

        @if ($start > 1)
        <li><a href="{{ $articles->url(1) }}">1</a></li>
        @if ($articles->currentPage() - 3 > 1)
        <li><span style="border: 0">...</span></li>
        @endif
        @endif

        @for ($i = $start; $i <= $end; $i++) @if ($i==$articles->currentPage())
            <li class="active"><span>{{ $i }}</span></li>
            @else
            <li><a href="{{ $articles->url($i) }}">{{ $i }}</a></li>
            @endif
            @endfor

            @if ($end < $articles->lastPage())
                @if ($articles->lastPage() - $articles->currentPage() > 2)
                <li><span style="border: 0">...</span></li>
                @endif
                <li><a href="{{ $articles->url($articles->lastPage()) }}">{{ $articles->lastPage() }}</a></li>
                @endif

                @if ($articles->hasMorePages())
                <li><a href="{{ $articles->nextPageUrl() }}" rel="next">&raquo;</a></li>
                @else
                <li class="disabled"><span>&raquo;</span></li>
                @endif
    </ul>
</div>
<!-- 否則有edit顯示編輯文章的文章列表 -->
@else
<div class="table-responsive container">
    <table class="table row mx-auto table-striped table-hover">
        <thead>
            <tr class="row">
                <th class="col-md-6 col-4">文章</th>
                <th class="col-md-2 col-2">狀態</th>
                <th class="col-md-2 col-4">發布時間</th>
                <th class="col-md-2 col-2">操作</th>
            </tr>
        </thead>
        @if($articles->isEmpty())
        <tbody>
            <tr class="row">
                <td class="col-md-12 col-12" style="text-align: center;">暫無文章</td>
            </tr>
        </tbody>
        @else
        <tbody>
            @foreach($articles as $article)
            <tr class="row">
                <td class="col-md-6 col-4">
                    <a href="{{ route('articles.show', $article) }}">
                        <div class="text-truncate">
                            <strong style="font-size: 1.1em">{{ $article->title }}</strong><br>
                            {{ $article->content }}
                        </div>
                    </a>
                </td>
                <td class="col-md-2 col-2">
                    <div style="line-height:3;">{{ $article->state === 'published' ? "發布" : "草稿" }}</div>
                </td>
                <td class="col-md-2 col-4">
                    <div class="text-truncate" style="line-height:3;">{{ $article->created_at }}</div>
                </td>
                <td class="col-md-2 col-2 index_set_box">
                    <a href="{{ route('articles.edit', ['article' => $article]) }}">
                        <button type="button" class="btn btn-success index_set">編輯</button>
                    </a>
                    <div style="display: inline-block;">
                    <form action="{{ route('articles.destroy', $article) }}" method="post">
                        @method('DELETE')
                        @csrf
                    <button type="submit" class="btn btn-danger index_set">刪除</button>
                </form></div>
                </td>
            </tr>
            @endforeach
        </tbody>
        @endif
    </table>
</div>
<!-- 分頁按鈕 -->
<div class="pagination">
    <ul>
        <!-- 前往上一頁 -->
        @if ($articles->onFirstPage())
        <li class="disabled"><span>&laquo;</span></li>
        @else
        <li><a href="{{ $articles->previousPageUrl() }}{{ $articles->previousPageUrl() ? '&' : '?' }}edit=true" rel="prev">&laquo;</a></li>
        @endif

        @php
        // 計算起始和結束頁數
        $start = max(1, $articles->currentPage() - 2);
        $end = min($articles->lastPage(), $articles->currentPage() + 2);
        @endphp

        <!-- 跳到第1頁 -->
        @if ($start > 1)
        <li><a href="{{ $articles->url(1) }}{{ $articles->url(1) ? '&' : '?' }}edit=true">1</a></li>
        <li><span style="border: 0">...</span></li>
        @endif

        <!-- 只要不是當前頁面都產生a標籤 -->
        @for ($i = $start; $i <= $end; $i++) @if ($i==$articles->currentPage())
            <li class="active"><span>{{ $i }}</span></li>
            @else
            <li><a href="{{ $articles->url($i) }}{{ $articles->url($i) ? '&' : '?' }}edit=true">{{ $i }}</a></li>
            @endif
            @endfor

            <!-- 跳到最後一頁 -->
            @if ($end < $articles->lastPage())
                <li><span style="border: 0">...</span></li>
                <li><a href="{{ $articles->url($articles->lastPage()) }}{{ $articles->url($articles->lastPage()) ? '&' : '?' }}edit=true">{{ $articles->lastPage() }}</a></li>
                @endif

                <!-- 前往下一頁 -->
                @if ($articles->hasMorePages())
                <li><a href="{{ $articles->nextPageUrl() }}{{ $articles->nextPageUrl() ? '&' : '?' }}edit=true" rel="next">&raquo;</a></li>
                @else
                <li class="disabled"><span>&raquo;</span></li>
                @endif
    </ul>
</div>
@endif
@endsection

resources/views/articles/show.blade.php
@extends('layouts/article')

@section('main')

      <div class="card border-success mb-3 container" style="padding: 0;">
        <div class="card-header text-success" style="font-size: 1.5em;">{{ $article->title }}</div>
        <div class="card-body">
          <h7 class="card-title">作者: {{ $article->user->name }}&nbsp;/&nbsp;發布日期: {{ $article->created_at->format('Y-m-d H:i:s') }}</h7>
          <div class="card-text mt-2">{!! nl2br(e($article->content)) !!}</div>
        </div>
      </div>

@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts/article')

@section('main')
<div class="alert alert-info container" role="alert">
  <i class="bi bi-lightbulb-fill"></i>&nbsp;使用 Laravel 製作文章管理功能
</div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])

        <!-- Styles -->
        @livewireStyles
    </head>
    <body class="font-sans antialiased">
        <x-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/article.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ asset('css/bootstrap-icons.min.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="{{ asset('css/article.css') }}">
  <title>Example</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ route('home') }}">Laravel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {{ request()->is('/') ? 'active' : '' }}" href="{{ route('home') }}">首頁</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ request()->is('articles') && !request()->has('edit') ? 'active' : '' }}" href="{{ route('articles.index') }}">文章列表</a>
          </li>
          <!-- 這裡的內容只會在使用者已登入時顯示 -->
          @auth
          <li class="nav-item">
            <a class="nav-link {{ request()->is('articles/create') ? 'active' : '' }}" href="{{ route('articles.create') }}">新增文章</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ request()->has('edit') ? 'active' : '' }}" href="{{ route('articles.index', ['edit' => true]) }}">你的文章</a>
          </li>
          @endauth
        </ul>

        <!-- 登入與註冊按鈕 -->
        @guest
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">登入</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">註冊</a>
          </li>
        </ul>
        @else
        <!-- 如果使用者已經登入，顯示使用者名稱和登出按鈕 -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <span class="nav-link">您好, {{ Auth::user()->name }}</span>
          </li>
          <li class="nav-item">
            <form action="{{ route('logout') }}" method="POST">
              @csrf
              <button type="submit" class="nav-link btn btn-link">登出</button>
            </form>
          </li>
        </ul>
        @endguest
        <!-- 搜尋表單 -->
        <form class="d-flex search_form" action="{{ route('articles.index') }}" method="get">
          <input class="form-control me-2" type="search" name="search" placeholder="搜尋文章" aria-label="Search" value="{{ isset($hasSearch) && $hasSearch ? $hasSearch : ''}}">
          <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
        </form>
      </div>
    </div>
  </nav>
  <main>
    @yield('main')
  </main>
  <footer class="bg-dark text-light text-center py-3">
    <p>&copy; <?php echo date("Y"); ?> wenhao。0800-888-888</p>
  </footer>
  <script src="{{ asset('js/bootstrap.min.js') }}"></script>
  <!-- <script src="{{ asset('js/app.js') }}"></script> -->
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])

        <!-- Styles -->
        @livewireStyles
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>

        @livewireScripts
    </body>
</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>